[package]
name = "crypto-bros"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
aes = "0.8.4"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_qs = "0.13.0"
urlencoding = "2.1.3"

[build-dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = "2.0.71"
